"""add host scan info

Revision ID: a09bc7cba9cb
Revises: d23d0e34312e
Create Date: 2026-03-11 02:43:37.387959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a09bc7cba9cb"
down_revision: Union[str, Sequence[str], None] = "d23d0e34312e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    host_status_enum = sa.Enum("new", "success", "failed", name="host_status_enum")
    host_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "hosts",
        sa.Column(
            "status",
            sa.Enum("new", "success", "failed", name="host_status_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "hosts", sa.Column("last_scan", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "last_scan")
    op.drop_column("hosts", "status")

    host_status_enum = sa.Enum("new", "success", "failed", name="host_status_enum")
    host_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
