"""init

Revision ID: d23d0e34312e
Revises:
Create Date: 2026-03-10 12:26:18.559817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d23d0e34312e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address"),
    )
    op.create_index(op.f("ix_hosts_id"), "hosts", ["id"], unique=False)
    op.create_table(
        "software",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="_software_name_version_uc"),
    )
    op.create_index(op.f("ix_software_id"), "software", ["id"], unique=False)
    op.create_table(
        "vms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("power_state", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("cpu", sa.Integer(), nullable=True),
        sa.Column("ram_mb", sa.Integer(), nullable=True),
        sa.Column("storage", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
    )
    op.create_index(op.f("ix_vms_id"), "vms", ["id"], unique=False)
    op.create_table(
        "vm_software",
        sa.Column("vm_id", sa.UUID(), nullable=False),
        sa.Column("software_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vm_id"],
            ["vms.id"],
        ),
        sa.PrimaryKeyConstraint("vm_id", "software_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vm_software")
    op.drop_index(op.f("ix_vms_id"), table_name="vms")
    op.drop_table("vms")
    op.drop_index(op.f("ix_software_id"), table_name="software")
    op.drop_table("software")
    op.drop_index(op.f("ix_hosts_id"), table_name="hosts")
    op.drop_table("hosts")
    # ### end Alembic commands ###
