[tool.poetry]
name = "vm-manager"
version = "0.1.0"
description = "API для управления хостами Hyper-V и ВМ"
readme = "README.md"

packages = [{include = "vm_api", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.0"
uvicorn = "^0.30.6"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
alembic = "^1.14.0"
pydantic = "^2.9.2"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"